# Generated by Django 5.2.5 on 2025-08-24 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI/Online Payment'), ('COD', 'Cash on Delivery')], max_length=10)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
